Repository opdev/opdev.github.io, pull requests merged in 2023-01, with the labels that each got.

#3 Fix build failure
  _includes/footer.html
Labels: size/XS

#11 Add recommended .gitignore and remove _site directory from source control
  .gitignore
  _site/OWNERS
  _site/README.md
  _site/about.html
  _site/assets/css/bootstrap.min.css
  _site/assets/css/default.css
  _site/assets/css/materialdesignicons.min.css
  _site/assets/css/metismenu.min.css
  _site/assets/css/owl-carousel.css
  _site/assets/css/style.css
  _site/assets/fonts/materialdesignicons-webfont.eot
  _site/assets/fonts/materialdesignicons-webfont.svg
  _site/assets/fonts/materialdesignicons-webfont.ttf
  _site/assets/fonts/materialdesignicons-webfont.woff
  _site/assets/fonts/materialdesignicons-webfont.woff2
  _site/assets/images/blog/blog-1.jpg
  _site/assets/images/blog/blog-2.jpg
  _site/assets/images/blog/blog-3.jpg
  _site/assets/images/blog/blog-4.jpg
  _site/assets/images/blog/blog-5.jpg
  _site/assets/images/favicon.ico
  _site/assets/images/logo.png
  _site/assets/images/photo.jpg
  _site/assets/images/red-logo.jpg
  _site/assets/images/user/user-1.png
  _site/assets/images/user/user-2.png
  _site/assets/images/user/user-3.png
  _site/assets/images/user/user-4.png
  _site/assets/images/user/user-5.png
  _site/assets/images/user/user-6.png
  _site/assets/images/works/img1.jpg
  _site/assets/images/works/img2.jpg
  _site/assets/images/works/img3.jpg
  _site/assets/js/bootstrap.min.js
  _site/assets/js/jquery.app.js
  _site/assets/js/jquery.easing.min.js
  _site/assets/js/jquery.min.js
  _site/assets/js/metisMenu.min.js
  _site/assets/js/owl.carousel.min.js
  _site/assets/js/popper.min.js
  _site/assets/js/scrollspy.min.js
  _site/assets/js/search-script.js
  _site/audio-post.html
  _site/contact.html
  _site/fruits/index.html
  _site/index.html
  _site/operators/index.html
  _site/posts/2022-12-26-podsecurity.html
  _site/posts/2022-12-31-kiwifruit.html
  _site/posts/2023-01-01-l5-op.html
  _site/posts/2023-01-10-bananas.html
  _site/posts/2023-01-11-apples.html
  _site/search.json
  _site/short-read/index.html
  _site/standard-post.html
  _site/video-post.html
Labels: size/XXL

#12 create a directory for articles/posts while in review mode
  _drafts/olm_overview.md
Labels: size/M

#15 Editorial feedback for olm post
  _drafts/olm_overview.md
Labels: size/M, lgtm

#14 Add Fedora ruby install directions and directions for adding posts
  README.md
Labels: size/M, approved

#17 Update README.md and Gemfile.lock
  Gemfile.lock
Labels: size/S

#23 Fixes #7, Removed tags from code
  _layouts/default.html
  _layouts/standard-post.html
  _layouts/tagpage.html
  _plugins/categoryfilter.rb
  _plugins/categoryhook.rb
  _plugins/tabhook.rb
  _plugins/tagfilter.rb
  _tags/fruits.md
  _tags/short-read.md
Labels: lgtm, size/L

#24 closes #8, closes #16, closes #18, closes #21;
  README.md
  _categories/documentation.md
  _categories/operators.md
  _categories/videos.md
  _config.yml
  _drafts/olm_overview.md
  _includes/footer.html
  _includes/navigation.html
  _layouts/categorypage.html
  _layouts/default.html
  _layouts/example-singlepage.html
  _layouts/standard-post.html
  _pages/about.html
  _pages/contact.html
  _pages/example-audio-post.html
  _pages/example-standard-post-.html
  _pages/example-video-post.html
  _pages/index.html
  _posts/2019-11-22-deepdive-in-operators.md
  _posts/2022-05-15-from-zero-to-autopilot.md
  _posts/2022-12-26-podsecurity.md
  _posts/2022-12-31-kiwifruit.md
  _posts/2023-01-01-l5-op.md
  _posts/2023-01-10-bananas.md
  _posts/2023-01-11-apples.md
Labels: size/XL

#25 Fixed links for categories
  _layouts/default.html
Labels: size/XS
